name: Archivage Java et rapport

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Générer nom de fichiers datés
        id: vars
        run: |
          echo "Q2_archive=Q2_archive_TOTO.txt" >> $GITHUB_OUTPUT

      - name: Vérifier intégrité de l’archive
        run: |
          echo "Rougeolle Henri" >> "${{ steps.vars.outputs.Q2_archive }}"          
          DATE=$(date +'%Y%m%d-%H%M%S')
          echo "date et heure : ${DATE}" >> "${{ steps.vars.outputs.Q2_archive }}"         
          cat TOTO.txt >> Q1_archive_TOTO.txt

      - name: Commit et push des résultats
        run: |
          git config --global user.name "HenriAku"
          git config --global user.email "rougeollehenri@gmail.com"
          git add "${{ steps.vars.outputs.Q1_archive }}" "${{ steps.vars.outputs.Q1_archive }}"
          git commit -m "Ajout archive et rapport du ${{ steps.vars.outputs.Q1_archive }}"
          git push
