name: Archivage Java et rapport

on: [push]
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Générer Q2_archive_TOTO.txt
        run: |
          echo "Rougeolle Henri" > Q2_archive_TOTO.txt
          echo "date et heure : $(date +'%Y%m%d-%H%M%S')" >> Q2_archive_TOTO.txt
          echo "--- Contenu de TOTO.txt ---" >> Q2_archive_TOTO.txt
          cat TOTO.txt >> Q2_archive_TOTO.txt
          echo "--- Taille de TOTO.txt ---" >> Q2_archive_TOTO.txt
          stat --format="Taille : %s octets" TOTO.txt >> Q2_archive_TOTO.txt

      - name: Commit et push des résultats
        run: |
          git config --global user.name "HenriAku"
          git config --global user.email "rougeollehenri@gmail.com"
          git add Q2_archive_TOTO.txt
          git commit -m "Ajout archive et rapport du $(date +'%Y%m%d-%H%M%S')"
          git push

